[package]
name = "leafwing-input-manager"
description = "A straightforward stateful input manager for the Bevy game engine."
version = "0.0.0"
authors = ["Leafwing Studios"]
homepage = "https://leafwing-studios.com/"
repository = "https://github.com/leafwing-studios/leafwing-input-manager"
license = "MIT + APACHE"
edition = "2021"
categories = ["games", "game-development"]
keywords = ["bevy"]
exclude = ["assets/**/*", "tools/**/*", "github/**/*"]

[profile.dev]
opt-level = 3

[workspace]
members = ["./", "tools/ci", "macros"]

[dependencies]
bevy = {version = "0.6", default-features = false, features = ["render"]}
petitset = {git = "https://github.com/leafwing-studios/petitset", commit = "fa0f411b7775047e57b3fadf90d66bf849123556"}
strum = "0.23"
strum_macros = "0.23"
leafwing_input_manager_macros = { path = "macros" }

[dev-dependencies]
bevy = {version = "0.6", default-features = true}
derive_more = "0.99"

[lib]
name = "leafwing_input_manager"
path = "src/lib.rs"